// leave off @2x/@3x
const images: any = {
  1: require('../images/1.jpeg'),
  2: require('../images/2.jpeg'),
  3: require('../images/3.jpeg'),
  4: require('../images/4.jpeg'),
  5: require('../images/5.jpeg'),
  6: require('../images/6.jpeg'),
  7: require('../images/7.jpeg'),
  8: require('../images/8.jpeg'),
  9: require('../images/9.jpeg'),
  10: require('../images/10.jpeg'),
  11: require('../images/11.jpeg'),
  12: require('../images/12.jpeg'),
  13: require('../images/13.jpeg'),
  14: require('../images/14.jpeg'),
  15: require('../images/15.jpeg'),
  16: require('../images/16.jpeg'),
  17: require('../images/17.jpeg'),
  18: require('../images/18.jpeg'),
  19: require('../images/19.jpeg'),
  20: require('../images/20.jpeg'),
  21: require('../images/21.jpeg'),
  22: require('../images/22.jpeg'),
  23: require('../images/23.jpeg'),
  24: require('../images/24.jpeg'),
  25: require('../images/25.jpeg'),
  26: require('../images/26.jpeg'),
  27: require('../images/27.jpeg'),
  28: require('../images/28.jpeg'),
  29: require('../images/29.jpeg'),
  30: require('../images/30.jpeg'),
  31: require('../images/31.jpeg'),
  32: require('../images/32.jpeg'),
  33: require('../images/33.jpeg'),
  34: require('../images/34.jpeg'),
  35: require('../images/35.jpeg'),
  36: require('../images/36.jpeg'),
  37: require('../images/37.jpeg'),
  38: require('../images/38.jpeg'),
  39: require('../images/39.jpeg'),
  40: require('../images/40.jpeg'),
  41: require('../images/41.jpeg'),
  42: require('../images/42.jpeg'),
  43: require('../images/43.jpeg'),
  44: require('../images/44.jpeg'),
  45: require('../images/45.jpeg'),
  46: require('../images/46.jpeg'),
  47: require('../images/47.jpeg'),
  48: require('../images/48.jpeg'),
};

export default images;
