export const images = [
  'https://res.hkjc.com/racingnews/wp-content/uploads/sites/3/2022/09/news_2022092701605_01.jpg',
  'https://res.hkjc.com/racingnews/wp-content/uploads/sites/3/2022/09/news_2022092701605_02.jpg',
  'https://res.hkjc.com/racingnews/wp-content/uploads/sites/3/2022/09/news_2022092701324_01.jpg',
  'https://res.hkjc.com/racingnews/wp-content/uploads/sites/3/2022/09/news_2022092701324_02.jpg',
  'https://corporate.hkjc.com/image/202108/EOG_WebBan_JC%20Equestrian_1406x626_V3_R1_ENG_OL.JPG',
  'https://corporate.hkjc.com/corporate/common/images/jc-news-and-activities/tokyo_olympics/olympic_header_900x403_e.jpg',
  'https://corporate.hkjc.com/corporate/common/english/images/jc-news-and-activities/equestrian/riders/thomasho-top.jpg',
  'https://corporate.hkjc.com/corporate/common/english/images/jc-news-and-activities/equestrian/riders/thomasho2-top.jpg',
  'https://corporate.hkjc.com/corporate/common/english/images/jc-news-and-activities/equestrian/riders/thomasho3-top.jpg',
  'https://corporate.hkjc.com/corporate/common/english/images/jc-news-and-activities/equestrian/riders/Natasha_Tse_01.jpg',
  'https://corporate.hkjc.com/corporate/common/english/images/jc-news-and-activities/equestrian/riders/Natasha_Tse_02.jpg',
  'https://corporate.hkjc.com/corporate/common/english/images/jc-news-and-activities/equestrian/riders/Natasha_Tse_03.jpg',
  'https://corporate.hkjc.com/corporate/common/english/images/jc-news-and-activities/equestrian/riders/Timothy_Tsang_01.jpg',
  'https://corporate.hkjc.com/corporate/common/english/images/jc-news-and-activities/equestrian/riders/Timothy_Tsang_02.jpg',
  'https://corporate.hkjc.com/corporate/common/english/images/jc-news-and-activities/equestrian/riders/Timothy_Tsang_03.jpg',
  'https://corporate.hkjc.com/corporate/common/images/jc-news-and-activities/shows-and-events.jpg',
  'https://corporate.hkjc.com/corporate/image/yfd/images/2022-08/yfd_2022081101100_902x401.jpg',
  'https://corporate.hkjc.com/corporate/image/yfd/images/2022-06/yfd_2022061501100_902x401.jpg',
  'https://corporate.hkjc.com/corporate/image/yfd/images/2020-06/yfd_2020060901100_001_902x401.jpg https://corporate.hkjc.com/corporate/common/images/jc-news-and-activities/junior-reporters-2.jpg',
  'https://corporate.hkjc.com/corporate/common/images/jc-news-and-activities/junior-reporters-3a.jpg',
  'https://corporate.hkjc.com/corporate/image/yfd/images/2020-02/yfd_20200212_001_902x401.jpg',
  'https://entertainment.hkjc.com/entertainment/common/images/go-racing/raceday-daytime.jpg',
  'https://entertainment.hkjc.com/entertainment/common/images/go-racing/sha-tin-racecourse/facilities-st-inner-circle-20212022-01.jpg',
  'https://entertainment.hkjc.com/entertainment/common/images/go-racing/sha-tin-racecourse/facilities-st-inner-circle-20212022-02.jpg',
  'https://corporate.hkjc.com/corporate/image/yfd/images/2020-02/yfd_20200212_001_902x401.jpg',
  'https://entertainment.hkjc.com/entertainment/common/images/go-racing/raceday-daytime.jpg',
];
